/** Declaration file generated by dts-gen */

export function BlueprintClass(schema: any, options?: any, { isArray = false }?: any): void;

export function BlueprintEmbedClass(instanceCls: any, options?: any): any;

export function validator(component: any, options?: any): any;

export namespace blueprint {
    function BlueprintClass(schema: any, options?: any, { isArray = false }?: any): void;

    function BlueprintEmbedClass(instanceCls: any, options?: any): any;

    function array(params: any, options?: any): any;

    function extend(component: any, params: any, options?: any, extendOptions?: any): any;

    function object(params: any, options?: any): any;

    namespace types {
        function any(paramsOrOptions: any): any;

        function bool(paramsOrOptions: any): any;

        function conditions(paramsOrOptions: any): any;

        function datetime(paramsOrOptions: any): any;

        function integer(paramsOrOptions: any): any;

        function number(paramsOrOptions: any): any;

        function options(paramsOrOptions: any): any;

        function string(paramsOrOptions: any): any;

        function transform(paramsOrOptions: any): any;

    }

}

export namespace types {
    function any(paramsOrOptions: any): any;

    function bool(paramsOrOptions: any): any;

    function conditions(paramsOrOptions: any): any;

    function datetime(paramsOrOptions: any): any;

    function integer(paramsOrOptions: any): any;

    function number(paramsOrOptions: any): any;

    function options(paramsOrOptions: any): any;

    function string(paramsOrOptions: any): any;

    function transform(paramsOrOptions: any): any;

}

